import React, { useState, useEffect } from 'react';
import {
  Bell,
  Filter,
  ArrowRight,
  ShieldCheck,
  ShieldAlert,
  Clock,
  RotateCcw
} from 'lucide-react';
import { fetchAlerts } from '../api';
import SeverityBadge from '../components/SeverityBadge';
import StatusBadge from '../components/StatusBadge';

export default function AlertsPage({ onSelectAlert }) {
  const [alerts, setAlerts] = useState([]);
  const [loading, setLoading] = useState(true);
  const [statusFilter, setStatusFilter] = useState('ALL');
  const [severityFilter, setSeverityFilter] = useState('ALL');

  const loadAlerts = async () => {
    setLoading(true);
    try {
      const data = await fetchAlerts({
        status: statusFilter === 'ALL' ? undefined : statusFilter,
        severity: severityFilter === 'ALL' ? undefined : severityFilter
      });
      setAlerts(data);
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    loadAlerts();
  }, [statusFilter, severityFilter]);

  const STATUS_TABS = [
    { id: 'ALL', label: 'All Alerts' },
    { id: 'OPEN', label: 'Open' },
    { id: 'IN_PROGRESS', label: 'In Progress' },
    { id: 'CLOSED', label: 'Closed' },
    { id: 'ESCALATED', label: 'Escalated' },
  ];

  return (
    <div className="page-container">
      <div className="page-header">
        <div>
          <h1 className="page-title">
            <Bell size={24} color="#f59e0b" />
            Security Alerts Queue
          </h1>
          <p className="page-description">
            Generated by detection rules from security event telemetry. Select an alert to begin L1 triage.
          </p>
        </div>

        <button className="btn btn-secondary btn-sm" onClick={loadAlerts}>
          <RotateCcw size={13} /> Refresh Queue
        </button>
      </div>

      {/* Filter Tabs and Controls */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: '1rem',
        borderBottom: '1px solid var(--border-color)',
        paddingBottom: '0.75rem'
      }}>
        {/* Status Tabs */}
        <div style={{ display: 'flex', gap: '0.5rem', flexWrap: 'wrap' }}>
          {STATUS_TABS.map((tab) => (
            <button
              key={tab.id}
              className={`btn btn-sm ${statusFilter === tab.id ? 'btn-primary' : 'btn-secondary'}`}
              onClick={() => setStatusFilter(tab.id)}
            >
              {tab.label}
            </button>
          ))}
        </div>

        {/* Severity Filter */}
        <div style={{ display: 'flex', alignItems: 'center', gap: '0.5rem' }}>
          <span style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>Severity:</span>
          <select
            className="form-select"
            value={severityFilter}
            onChange={(e) => setSeverityFilter(e.target.value)}
            style={{ padding: '0.3rem 0.6rem', fontSize: '0.8rem' }}
          >
            <option value="ALL">All Severities</option>
            <option value="Medium">Medium</option>
            <option value="Low">Low</option>
          </select>
        </div>
      </div>

      {/* Alerts Table */}
      <div className="table-card">
        <div className="table-responsive">
          <table className="soc-table">
            <thead>
              <tr>
                <th>Alert ID</th>
                <th>Alert Name</th>
                <th>Severity</th>
                <th>Timestamp</th>
                <th>User</th>
                <th>Host</th>
                <th>Source IP</th>
                <th>Events</th>
                <th>Status</th>
                <th style={{ textAlign: 'right' }}>Triage</th>
              </tr>
            </thead>
            <tbody>
              {loading ? (
                <tr>
                  <td colSpan={10} style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-muted)' }}>
                    Loading alerts...
                  </td>
                </tr>
              ) : alerts.length === 0 ? (
                <tr>
                  <td colSpan={10} style={{ textAlign: 'center', padding: '2rem', color: 'var(--text-muted)' }}>
                    No alerts match the criteria.
                  </td>
                </tr>
              ) : (
                alerts.map((al) => (
                  <tr
                    key={al.id}
                    style={{ cursor: 'pointer' }}
                    onClick={() => onSelectAlert(al.id)}
                  >
                    <td>
                      <span className="mono-cell" style={{ fontWeight: 700, color: '#38bdf8' }}>
                        {al.id}
                      </span>
                    </td>
                    <td>
                      <div style={{ fontWeight: 600, color: '#fff' }}>{al.name}</div>
                      <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)' }}>
                        {al.description}
                      </div>
                    </td>
                    <td>
                      <SeverityBadge severity={al.severity} />
                    </td>
                    <td>
                      <span className="mono-cell" style={{ display: 'flex', alignItems: 'center', gap: '0.35rem' }}>
                        <Clock size={12} color="var(--text-muted)" />
                        {al.timestamp?.replace('T', ' ').slice(0, 19)}
                      </span>
                    </td>
                    <td>
                      <span className="mono-cell" style={{ color: '#60a5fa' }}>{al.user}</span>
                    </td>
                    <td>
                      <span className="mono-cell">{al.host}</span>
                    </td>
                    <td>
                      <span className="mono-cell">{al.source_ip}</span>
                    </td>
                    <td>
                      <span className="badge" style={{ background: 'rgba(255,255,255,0.06)', color: 'var(--text-primary)' }}>
                        {al.event_count}
                      </span>
                    </td>
                    <td>
                      <StatusBadge status={al.status} />
                    </td>
                    <td style={{ textAlign: 'right' }}>
                      <button
                        className="btn btn-primary btn-sm"
                        onClick={(e) => {
                          e.stopPropagation();
                          onSelectAlert(al.id);
                        }}
                      >
                        Investigate
                        <ArrowRight size={12} />
                      </button>
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
